logo_image = Image("zzz.png");

pos_x = Window.GetWidth()/2 - logo_image.GetWidth()/2;
pos_y = Window.GetHeight()/2 - logo_image.GetHeight()/2;

logo_sprite = Sprite(logo_image);
logo_sprite.SetX(pos_x);
logo_sprite.SetY(pos_y);

Window.SetBackgroundTopColor (0.9, 0.9, 0.9);
Window.SetBackgroundBottomColor (0.9, 0.9, 0.9);

fun refresh_callback ()
{
  logo_sprite.SetOpacity(1);
  # spr.SetZ(15);
}

Plymouth.SetRefreshFunction (refresh_callback);
